// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Board");

function make(activeIx, onClick, clickedIx, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("div", {
                          className: "board"
                        }, Belt_Array.map(Belt_Array.range(0, 8), (function (ix) {
                                console.log(clickedIx);
                                var match = ix === activeIx;
                                var moleClassName = match ? "mole visible" : "mole";
                                var match$1 = clickedIx === ix;
                                return React.createElement("div", {
                                            key: String(ix),
                                            className: "board-item"
                                          }, React.createElement("div", {
                                                className: moleClassName,
                                                onClick: (function (param) {
                                                    return Curry._1(onClick, ix);
                                                  })
                                              }), React.createElement("div", {
                                                className: "ground"
                                              }), match$1 ? React.createElement("div", {
                                                  className: "hit"
                                                }) : null);
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
